#!/usr/bin/env tsx
/**
 * API reference generator.
 *
 * Builds the running-mode Express app via `createApp('running')`, which
 * is the single place where ALL route modules register on the manifest:
 * 24 modules register when `routes/index.ts` is imported, and four more
 * (feed, sitemap, unsubscribe, setup) register inside `createApp` itself.
 * After construction we read the live `manifest()` and emit:
 *
 *   docs/api-manifest.json — machine-readable (client SDK codegen input)
 *   docs/API.md            — human-readable reference
 *
 * Env handling: importing `../src/app` pulls in `../src/config`, which is
 * a zod-tolerant loader (it reads backend/.env via dotenv and supplies
 * safe defaults). No DB/Redis connections happen at import or inside
 * `createApp` — index.ts owns those — so constructing the app here is a
 * pure, side-effect-free way to populate the manifest. We never call
 * `app.listen`.
 *
 * Usage: npm run docs:api
 */
import { writeFileSync, } from 'fs';
import path from 'path';
import { ERROR_CODES, } from '@rw/cms-shared';
import { createApp, } from '../src/app';
import { manifest, } from '../src/api/registry';

interface ManifestRoute {
    method: string;
    path: string;
    absolutePath: string;
    auth: string;
    summary: string;
}

interface ManifestModule {
    module: string;
    mountPath: string;
    routes: ManifestRoute[];
}

const REPO_ROOT = path.resolve(process.cwd(), '..', '..',);
const DOCS_DIR = path.join(REPO_ROOT, 'docs',);

function escapeCell(value: string,): string {
    // Pipes would break the markdown table; paths/summaries never contain
    // newlines, but escape pipes defensively.
    return value.replace(/\|/g, '\\|',);
}

function renderModuleSection(mod: ManifestModule,): string {
    const lines: string[] = [];
    lines.push(`## ${mod.module}`,);
    lines.push('',);
    const mount = mod.mountPath === '' ? '(site root)' : `\`${mod.mountPath}\``;
    lines.push(`Mount path: ${mount}`,);
    lines.push('',);
    lines.push('| Method | Path | Auth | Summary |',);
    lines.push('| --- | --- | --- | --- |',);
    for (const r of mod.routes) {
        lines.push(
            `| ${r.method} | \`${escapeCell(r.absolutePath,)}\` | ${r.auth} | ${escapeCell(r.summary,)} |`,
        );
    }
    lines.push('',);
    return lines.join('\n',);
}

function renderApiMarkdown(generatedAt: string, modules: ManifestModule[], totalRoutes: number,): string {
    const errorCodeList = ERROR_CODES.map((c,) => `- \`${c}\``,).join('\n',);

    const intro = `# API Reference

> Generated by \`npm run docs:api\` — do not edit by hand.
>
> Generated at: ${generatedAt}
> Modules: ${modules.length} · Routes: ${totalRoutes}

SiteSurge exposes a full REST surface under \`/api/v1\`. External clients
(servers, scripts, the bundled SPA) all talk to the same endpoints. This
document is generated from the live route manifest, so it never drifts
from the running server.

## Envelope

Every \`/api/v1\` endpoint responds in a single envelope.

Success:

\`\`\`json
{ "success": true, "data": <payload>, "meta": { } }
\`\`\`

\`meta\` is present only on paginated list endpoints.

Error:

\`\`\`json
{ "success": false, "error": { "code": "NOT_FOUND", "message": "…", "details": { } } }
\`\`\`

\`details\` is optional and carries field-level validation info where
relevant.

## Error codes

Clients switch on \`error.code\`. Adding a code is backwards-compatible;
renaming or removing one is a breaking change.

${errorCodeList}

## Auth tiers

Each route declares one auth tier. The framework enforces it.

| Tier | Who can call | Notes |
| --- | --- | --- |
| \`public\` | Anyone, no credentials | No auth header required. |
| \`optional\` | Anyone; richer response when authenticated | Accepts a user JWT, a cookie session, or an \`ssk_\` API key as a machine client. Response is shaped by role — admins/keys see drafts and unpublished data. |
| \`user\` | Any authenticated user | Bearer JWT or cookie session. |
| \`admin\` | Admin role, or a scoped API key | Accepts an admin JWT/cookie OR an \`ssk_\` API key whose scope covers the operation. |
| \`apiKey\` | Same as \`admin\` | Semantic marker for routes designed primarily for machine clients. |

API-key scopes are ordered \`read < write < admin\`. A \`GET\` requires
\`read\` or higher; a mutating request (\`POST\`/\`PUT\`/\`PATCH\`/\`DELETE\`)
requires \`write\` or higher. Key-management routes require a full admin
session — a key cannot manage keys.

## Authentication

**User JWT.** \`POST /api/v1/auth/login\` returns an \`AuthResponse\` with
\`accessToken\` (15 min) and \`refreshToken\` (7 d) in the body, and also sets
httpOnly cookies for browsers. Send the access token as
\`Authorization: Bearer <accessToken>\`. When it expires, call
\`POST /api/v1/auth/refresh\` to mint a new pair.

**CSRF.** Bearer- and API-key-authenticated requests bypass CSRF. Only
cookie-mode state-changing requests need CSRF: a cookie-less client that
relies on the session cookie must first issue one \`GET\` to receive the
\`csrf-token\` cookie, then echo it back in the \`x-csrf-token\` header on
subsequent \`POST\`/\`PUT\`/\`PATCH\`/\`DELETE\` calls. Machine clients should
simply use Bearer or API-key auth and skip the CSRF round-trip entirely.

**API keys.** Create a key in the admin UI under **Settings → API Keys**.
Send it as \`Authorization: Bearer ssk_…\`. Keys carry a scope
(\`read\`/\`write\`/\`admin\`) and are the recommended auth mode for headless
integrations.

## Pagination

List endpoints return a \`meta\` object alongside \`data\`:

\`\`\`json
{ "page": 1, "limit": 20, "total": 137, "totalPages": 7 }
\`\`\`

Pass \`page\` and \`limit\` (and, where supported, \`sortBy\`/\`sortOrder\`) as
query parameters.

## Raw endpoints

A few endpoints intentionally fall outside the JSON envelope because they
serve a different content type or protocol:

- \`/feed.xml\` and the \`/api/v1\` alias — RSS 2.0 XML.
- \`/sitemap.xml\` — sitemap XML.
- \`/u/:token\` and \`/lists/:slug/confirm/:token\` — unsubscribe / double-opt-in HTML.
- \`/api/v1/payments/webhook\` — Stripe webhook (raw body, signature-verified).
- Form CSV export — \`text/csv\` download.

These return XML/HTML/CSV or a redirect rather than the \`{ success, data }\`
envelope.

---
`;

    const sections = modules.map(renderModuleSection,).join('\n',);
    return `${intro}\n${sections}`;
}

function main(): void {
    // Construct the running-mode app purely to trigger module registration
    // on the manifest. No server is started; no DB/Redis connections occur.
    createApp('running',);

    const modules = manifest() as ManifestModule[];
    const sorted = [...modules,].sort((a, b,) => a.module.localeCompare(b.module,),);
    const totalRoutes = sorted.reduce((sum, m,) => sum + m.routes.length, 0,);
    const generatedAt = new Date().toISOString();

    const manifestDoc = {
        generatedAt,
        totalModules: sorted.length,
        totalRoutes,
        modules: sorted,
    };

    const manifestPath = path.join(DOCS_DIR, 'api-manifest.json',);
    const apiMdPath = path.join(DOCS_DIR, 'API.md',);

    writeFileSync(manifestPath, `${JSON.stringify(manifestDoc, null, 2,)}\n`,);
    writeFileSync(apiMdPath, renderApiMarkdown(generatedAt, sorted, totalRoutes,),);

    // eslint-disable-next-line no-console
    console.log(
        `Wrote ${path.relative(REPO_ROOT, manifestPath,)} and ${path.relative(REPO_ROOT, apiMdPath,)} — ` +
            `${sorted.length} modules, ${totalRoutes} routes.`,
    );
}

main();
