/**
 * Regenerate media thumbnails that lost their TRANSPARENCY.
 *
 * Thumbnails used to be written as JPEG for every image; JPEG has no alpha,
 * so a transparent PNG/WebP got a black background in the media library.
 * New uploads now get a PNG thumbnail when the image has alpha
 * (services/media.ts createThumbnail). This fixes the existing ones.
 *
 * Each new thumbnail goes to a NEW key (`uploads/thumb_v2_<file>`) and the row
 * points at it: uploads are served `immutable`, so overwriting the old key
 * would keep the black version in CDN + browser caches for a year.
 *
 *   tsx scripts/regenerate-thumbnails.ts            # dry run (lists what it would fix)
 *   tsx scripts/regenerate-thumbnails.ts --apply    # do it
 */
import 'dotenv/config';
import fs from 'fs/promises';
import os from 'os';
import path from 'path';
import sharp from 'sharp';
import { closePool, query, } from '../src/db/client';
import { IMMUTABLE_CACHE, isObjectStore, resolveStorageProvider, } from '../src/services/storage';

const APPLY = process.argv.includes('--apply',);

async function main(): Promise<void> {
    const store = await resolveStorageProvider();
    if (!isObjectStore(store,)) {
        console.log('Local storage: thumbnails are regenerated by re-uploading; nothing to do here.',);
        return;
    }
    const rows = (await query<{ id: string; filename: string; url: string; thumbnail_url: string | null; }>(
        `SELECT id, filename, url, thumbnail_url FROM media
          WHERE mime_type IN ('image/png', 'image/webp', 'image/avif', 'image/tiff')
            AND thumbnail_url IS NOT NULL AND thumbnail_url NOT LIKE '%/thumb_v2_%'
          ORDER BY created_at`,
    )).rows;
    console.log(`${rows.length} candidate image(s); ${APPLY ? 'applying' : 'dry run'}.`,);
    const tmp = await fs.mkdtemp(path.join(os.tmpdir(), 'thumbs-',),);
    let fixed = 0;
    for (const r of rows) {
        try {
            const res = await fetch(r.url,);
            if (!res.ok) { console.log(`skip ${r.filename}: original HTTP ${res.status}`,); continue; }
            const buf = Buffer.from(await res.arrayBuffer(),);
            const { hasAlpha, } = await sharp(buf,).metadata();
            if (!hasAlpha) continue;
            const key = `uploads/thumb_v2_${r.filename}`;
            if (!APPLY) { console.log(`would fix ${r.filename}`,); fixed++; continue; }
            const out = path.join(tmp, `thumb_v2_${r.filename}.png`,);
            await sharp(buf,).resize(300, null, { withoutEnlargement: true, },).png({ compressionLevel: 9, adaptiveFiltering: true, },).toFile(out,);
            await store.putFile(key, out, { contentType: 'image/png', cacheControl: IMMUTABLE_CACHE, },);
            await query(`UPDATE media SET thumbnail_url = $2, updated_at = NOW() WHERE id = $1`, [r.id, store.publicUrl(key,),],);
            console.log(`fixed ${r.filename}`,);
            fixed++;
        } catch (e) {
            console.log(`error ${r.filename}: ${(e as Error).message}`,);
        }
    }
    await fs.rm(tmp, { recursive: true, force: true, },);
    console.log(`${APPLY ? 'Fixed' : 'Would fix'} ${fixed} thumbnail(s).`,);
}

main().catch((e,) => { console.error(e,); process.exitCode = 1; },).finally(() => void closePool(),);
