import { Router, } from 'express';
import auditRoutes from './audit';
import authRoutes from './auth';
import blockStylesRoutes from './blockStyles';
import campaignsRoutes from './campaigns';
import connectionsRoutes from './connections';
import dashboardRoutes from './dashboard';
import devRoutes from './dev';
import fontsRoutes from './fonts';
import formsRoutes from './forms';
import healthRoutes from './health';
import mailingListsRoutes, { publicMailingListsRouter, } from './mailingLists';
import mailTemplatesRoutes from './mailTemplates';
import mediaRoutes from './media';
import messagesRoutes from './messages';
import pagesRoutes from './pages';
import paymentsRoutes from './payments';
import postsRoutes from './posts';
import searchRoutes from './search';
import settingsRoutes from './settings';
import sitemapRoutes from './sitemap';
import socialRoutes from './social';
import usersRoutes from './users';

const router = Router();

router.use('/auth', authRoutes,);
router.use('/block-styles', blockStylesRoutes,);
router.use('/pages', pagesRoutes,);
router.use('/posts', postsRoutes,);
router.use('/campaigns', campaignsRoutes,);
router.use('/connections', connectionsRoutes,);
router.use('/payments', paymentsRoutes,);
router.use('/forms', formsRoutes,);
router.use('/users', usersRoutes,);
router.use('/messages', messagesRoutes,);
router.use('/media', mediaRoutes,);
router.use('/social', socialRoutes,);
router.use('/settings', settingsRoutes,);
router.use('/search', searchRoutes,);
router.use('/health', healthRoutes,);
router.use('/sitemap', sitemapRoutes,);
router.use('/audit', auditRoutes,);
router.use('/dashboard', dashboardRoutes,);
router.use('/dev', devRoutes,);
router.use('/fonts', fontsRoutes,);
router.use('/mailing-lists', mailingListsRoutes,);
router.use('/mail-templates', mailTemplatesRoutes,);
router.use('/lists', publicMailingListsRouter,);

export default router;
