import { Router, } from 'express';
import { registerModule, } from '../api/registry';
import { apiKeysRoutes, } from './apiKeys';
import { auditRoutes, } from './audit';
import authRoutes from './auth';
import { blockStylesRoutes, } from './blockStyles';
import campaignsRoutes from './campaigns';
import connectionsRoutes from './connections';
import { dashboardRoutes, } from './dashboard';
import { devRoutes, } from './dev';
import { fontsRoutes, } from './fonts';
import formsRoutes from './forms';
import { healthRoutes, } from './health';
import mailingListsRoutes, { publicMailingListsRouter, } from './mailingLists';
import mailSendRoutes from './mailSend';
import mailTemplatesRoutes from './mailTemplates';
import mediaRoutes from './media';
import messagesRoutes from './messages';
import pagesRoutes from './pages';
import paymentsRoutes from './payments';
import { postsRoutes, } from './posts';
import { searchRoutes, } from './search';
import settingsRoutes from './settings';
import sitemapRoutes from './sitemap';
import socialRoutes from './social';
import usersRoutes from './users';

const router = Router();

router.use('/auth', authRoutes,);
router.use('/block-styles', registerModule('block-styles', blockStylesRoutes,),);
router.use('/pages', pagesRoutes,);
router.use('/posts', registerModule('posts', postsRoutes,),);
router.use('/campaigns', campaignsRoutes,);
router.use('/connections', connectionsRoutes,);
router.use('/payments', paymentsRoutes,);
router.use('/forms', formsRoutes,);
router.use('/users', usersRoutes,);
router.use('/messages', messagesRoutes,);
router.use('/media', mediaRoutes,);
router.use('/social', socialRoutes,);
router.use('/settings', settingsRoutes,);
router.use('/search', registerModule('search', searchRoutes,),);
router.use('/health', registerModule('health', healthRoutes,),);
router.use('/sitemap', sitemapRoutes,);
router.use('/api-keys', registerModule('api-keys', apiKeysRoutes,),);
router.use('/audit', registerModule('audit', auditRoutes,),);
router.use('/dashboard', registerModule('dashboard', dashboardRoutes,),);
router.use('/dev', registerModule('dev', devRoutes,),);
router.use('/fonts', registerModule('fonts', fontsRoutes,),);
router.use('/mailing-lists', mailingListsRoutes,);
router.use('/mail-templates', mailTemplatesRoutes,);
router.use('/mail', mailSendRoutes,);
router.use('/lists', publicMailingListsRouter,);

export default router;
