/**
 * The selector subset the email inliner can decide from an opening tag and the
 * stack of elements enclosing it.
 *
 * Split out of `customCss.ts`, which had grown three jobs: parsing selectors,
 * matching them against an HTML string, and deciding what email can deliver.
 * This is the first — a model plus its parser, with no opinion about email.
 */

/**
 * One compound selector — everything that must be true of a SINGLE element.
 *
 * `a.btn.large#x` → `{ tag: 'a', classes: ['btn','large'], id: 'x' }`.
 */
export interface Compound {
    /** Lower-case tag name, or '' for "any tag" (a bare `.class` / `#id`). */
    tag: string;
    /** Every class the element must carry. */
    classes: string[];
    /** Required id, if any. */
    id: string;
}

/** How a compound relates to the one before it. */
export type Combinator = 'descendant' | 'child';

/**
 * A selector as a chain: the LAST compound must match the element itself, and
 * each earlier one must match an ancestor — any ancestor for `descendant`, the
 * immediately enclosing one for `child`.
 */
export interface SelectorChain {
    /** The element's own requirements. */
    subject: Compound;
    /** Ancestor requirements, innermost FIRST (reading the selector right to
     *  left, which is the order the match walks the open-tag stack). */
    ancestors: Array<{ combinator: Combinator; compound: Compound; }>;
}

/**
 * One compound: an optional tag followed by any number of `.class` / `#id`.
 *
 * Deliberately strict — no pseudo-classes, no attribute selectors, no `*`.
 * Those cannot be decided from an opening tag alone (or, for `:hover`, cannot
 * exist in an inline style at all), so they fall through to the stylesheet
 * rather than being half-honoured.
 */
const COMPOUND = /^([a-z][\w-]*)?((?:[.#][\w-]+)*)$/i;

export function parseCompound(sel: string,): Compound | null {
    const m = COMPOUND.exec(sel.trim(),);
    if (!m) return null;
    const [, tag, rest,] = m;
    if (!tag && !rest) return null; // the empty string matches everything
    const classes: string[] = [];
    let id = '';
    for (const part of rest.match(/[.#][\w-]+/g,) ?? []) {
        if (part[0] === '.') classes.push(part.slice(1,),);
        else id = part.slice(1,);
    }
    return { tag: (tag ?? '').toLowerCase(), classes, id, };
}

/**
 * Parse a full selector into a chain, or null when any part is beyond us.
 *
 * Descendant (` `) and child (`>`) are supported because both can be decided
 * from the stack of currently-open tags while scanning the markup — the mail
 * HTML is generated by this renderer, so it is well formed and that stack is
 * reliable. Sibling combinators (`+`, `~`) are NOT: they need the elements
 * already closed beside the subject, which the scan has thrown away.
 */
export function parseSelectorChain(selector: string,): SelectorChain | null {
    // Normalise `a>b` and `a > b` alike, keeping the combinators as tokens.
    const tokens = selector.trim().replace(/\s*>\s*/g, ' > ',).split(/\s+/,).filter(Boolean,);
    if (tokens.length === 0) return null;
    // Belt and braces: `+`/`~` already fail `parseCompound`, so this changes
    // nothing today. It is here so that widening COMPOUND later cannot let a
    // sibling combinator through the back door and be silently mis-matched.
    if (tokens.some(t => t === '+' || t === '~')) return null;

    const parts: Array<{ combinator: Combinator; compound: Compound; }> = [];
    let pendingCombinator: Combinator = 'descendant';
    for (const token of tokens) {
        if (token === '>') {
            pendingCombinator = 'child';
            continue;
        }
        const compound = parseCompound(token,);
        if (!compound) return null;
        parts.push({ combinator: pendingCombinator, compound, },);
        pendingCombinator = 'descendant';
    }
    if (parts.length === 0) return null;

    const subject = parts[parts.length - 1].compound;
    // Innermost first: the ancestor nearest the subject is checked first, which
    // is the order `matchesChain` walks the stack.
    const ancestors = parts
        .slice(0, -1,)
        .map((p, i,) => ({ combinator: parts[i + 1].combinator, compound: p.compound, }))
        .reverse();
    return { subject, ancestors, };
}
