/**
 * A block's operator-authored Custom CSS, translated for email.
 *
 * On the web the whole sheet is scoped and injected as a `<style>`. Email has
 * no such luxury: Gmail strips `<style>` in a forwarded message, several
 * clients drop it outright, and Outlook's Word engine ignores most of what
 * survives. Inline `style` attributes are the only thing that works
 * everywhere — which is why every other part of this renderer is inline.
 *
 * So the sheet is SPLIT by how reliably each rule can be delivered:
 *
 *   1. `&` and bare declarations → merged into the block's own `<td>` style.
 *      Completely reliable, and the shape most operators actually write.
 *   2. Tag / class / id compounds joined by descendant (` `) or child (`>`)
 *      combinators — `p`, `.price`, `a.btn`, `td a img`, `div > p` → inlined
 *      onto every matching element in the block's own markup.
 *   3. Everything else — pseudo-classes, attribute selectors, sibling
 *      combinators, media queries — → the head `<style>`, scoped to this
 *      block. A progressive enhancement, exactly like the per-breakpoint rules
 *      next door, and not honoured by every client.
 *
 * Why group 2 can include combinators without a DOM: `applyInlineRules` scans
 * the markup in order and keeps the stack of currently-open elements, so an
 * ancestor step is answered from real structure. That stack is trustworthy
 * because this HTML is generated by the renderers next door — it is well
 * formed by construction.
 *
 * Group 3 is where certainty runs out rather than where effort did. A sibling
 * combinator needs elements the scan has already closed and discarded; a
 * pseudo-class has no inline equivalent at all. Guessing at those would
 * silently corrupt the messages it got wrong, which is worse than a rule that
 * plainly does or does not arrive.
 *
 * Precedence: the operator's declarations are merged LAST, so they beat what
 * this renderer emitted. That mirrors the web, where custom CSS closes the
 * block's cascade layer and overrides the style controls above it.
 */
import { parseCssRules, scopeCss, } from '@sitesurge/types';

/**
 * One compound selector — everything that must be true of a SINGLE element.
 *
 * `a.btn.large#x` → `{ tag: 'a', classes: ['btn','large'], id: 'x' }`.
 */
interface Compound {
    /** Lower-case tag name, or '' for "any tag" (a bare `.class` / `#id`). */
    tag: string;
    /** Every class the element must carry. */
    classes: string[];
    /** Required id, if any. */
    id: string;
}

/** How a compound relates to the one before it. */
type Combinator = 'descendant' | 'child';

/**
 * A selector as a chain: the LAST compound must match the element itself, and
 * each earlier one must match an ancestor — any ancestor for `descendant`, the
 * immediately enclosing one for `child`.
 */
interface SelectorChain {
    /** The element's own requirements. */
    subject: Compound;
    /** Ancestor requirements, innermost FIRST (reading the selector right to
     *  left, which is the order the match walks the open-tag stack). */
    ancestors: Array<{ combinator: Combinator; compound: Compound; }>;
}

export interface InlineRule {
    match: SelectorChain;
    decls: Record<string, string>;
}

export interface EmailCustomCss {
    /** Declarations for the block's own cell. */
    cell: Record<string, string>;
    /** Rules to inline onto elements inside the block's markup. */
    inline: InlineRule[];
    /** Rules that could not be inlined, already scoped to this block. */
    stylesheet: string;
}

const EMPTY: EmailCustomCss = { cell: {}, inline: [], stylesheet: '', };

/**
 * One compound: an optional tag followed by any number of `.class` / `#id`.
 *
 * Deliberately strict — no pseudo-classes, no attribute selectors, no `*`.
 * Those cannot be decided from an opening tag alone (or, for `:hover`, cannot
 * exist in an inline style at all), so they fall through to the stylesheet
 * rather than being half-honoured.
 */
const COMPOUND = /^([a-z][\w-]*)?((?:[.#][\w-]+)*)$/i;

function parseCompound(sel: string,): Compound | null {
    const m = COMPOUND.exec(sel.trim(),);
    if (!m) return null;
    const [, tag, rest,] = m;
    if (!tag && !rest) return null; // the empty string matches everything
    const classes: string[] = [];
    let id = '';
    for (const part of rest.match(/[.#][\w-]+/g,) ?? []) {
        if (part[0] === '.') classes.push(part.slice(1,),);
        else id = part.slice(1,);
    }
    return { tag: (tag ?? '').toLowerCase(), classes, id, };
}

/**
 * Parse a full selector into a chain, or null when any part is beyond us.
 *
 * Descendant (` `) and child (`>`) are supported because both can be decided
 * from the stack of currently-open tags while scanning the markup — the mail
 * HTML is generated by this renderer, so it is well formed and that stack is
 * reliable. Sibling combinators (`+`, `~`) are NOT: they need the elements
 * already closed beside the subject, which the scan has thrown away.
 */
function parseSelectorChain(selector: string,): SelectorChain | null {
    // Normalise `a>b` and `a > b` alike, keeping the combinators as tokens.
    const tokens = selector.trim().replace(/\s*>\s*/g, ' > ',).split(/\s+/,).filter(Boolean,);
    if (tokens.length === 0) return null;
    // Belt and braces: `+`/`~` already fail `parseCompound`, so this changes
    // nothing today. It is here so that widening COMPOUND later cannot let a
    // sibling combinator through the back door and be silently mis-matched.
    if (tokens.some(t => t === '+' || t === '~')) return null;

    const parts: Array<{ combinator: Combinator; compound: Compound; }> = [];
    let pendingCombinator: Combinator = 'descendant';
    for (const token of tokens) {
        if (token === '>') {
            pendingCombinator = 'child';
            continue;
        }
        const compound = parseCompound(token,);
        if (!compound) return null;
        parts.push({ combinator: pendingCombinator, compound, },);
        pendingCombinator = 'descendant';
    }
    if (parts.length === 0) return null;

    const subject = parts[parts.length - 1].compound;
    // Innermost first: the ancestor nearest the subject is checked first, which
    // is the order `matchesChain` walks the stack.
    const ancestors = parts
        .slice(0, -1,)
        .map((p, i,) => ({ combinator: parts[i + 1].combinator, compound: p.compound, }))
        .reverse();
    return { subject, ancestors, };
}

/**
 * Split a declaration block into `{ prop: value }`.
 *
 * Tracks quotes and parentheses so a `;` inside `url(a;b)` or `content: ";"`
 * does not cut a declaration in half.
 */
export function parseDeclarations(body: string,): Record<string, string> {
    const out: Record<string, string> = {};
    let depth = 0;
    let cur = '';
    let i = 0;
    const flush = () => {
        const idx = cur.indexOf(':',);
        if (idx > 0) {
            const prop = cur.slice(0, idx,).trim().toLowerCase();
            const value = cur.slice(idx + 1,).trim();
            // A trailing `!important` is meaningless in an inline style that
            // already wins, and noise in the attribute.
            if (prop && value) out[prop] = value.replace(/\s*!important\s*$/i, '',);
        }
        cur = '';
    };
    while (i < body.length) {
        const ch = body[i];
        if (ch === '"' || ch === "'") {
            const end = findStringEnd(body, i,);
            cur += body.slice(i, end,);
            i = end;
            continue;
        }
        if (ch === '/' && body[i + 1] === '*') {
            const end = body.indexOf('*/', i + 2,);
            i = end === -1 ? body.length : end + 2;
            continue;
        }
        if (ch === '(') depth += 1;
        else if (ch === ')') depth -= 1;
        if (ch === ';' && depth === 0) {
            flush();
            i += 1;
            continue;
        }
        cur += ch;
        i += 1;
    }
    flush();
    return out;
}

function findStringEnd(s: string, start: number,): number {
    const quote = s[start];
    let i = start + 1;
    while (i < s.length) {
        if (s[i] === '\\') {
            i += 2;
            continue;
        }
        if (s[i] === quote) return i + 1;
        i += 1;
    }
    return s.length;
}

/**
 * Classify one block's custom CSS into the three delivery groups.
 *
 * `scope` is the selector the leftover stylesheet is scoped to — for email,
 * `[data-block-id="…"]` (there is no `.block` wrapper in a table layout).
 */
export function planCustomCss(css: string | null | undefined, scope: string,): EmailCustomCss {
    if (!css || !css.trim()) return EMPTY;

    const cell: Record<string, string> = {};
    const inline: InlineRule[] = [];
    const leftover: string[] = [];

    for (const rule of parseCssRules(css,)) {
        if (rule.atRule) {
            // A media/supports query cannot be inlined by definition — an
            // inline style has no condition attached to it.
            leftover.push(`${rule.selector}{${rule.body}}`,);
            continue;
        }
        const decls = parseDeclarations(rule.body,);
        // Selector-less declarations mean "this block".
        if (!rule.selector) {
            Object.assign(cell, decls,);
            continue;
        }
        for (const one of rule.selector.split(',',).map(s => s.trim()).filter(Boolean,)) {
            if (one === '&') {
                Object.assign(cell, decls,);
                continue;
            }
            const chain = parseSelectorChain(one,);
            if (chain && Object.keys(decls,).length) inline.push({ match: chain, decls, },);
            else leftover.push(`${one}{${rule.body}}`,);
        }
    }

    return { cell, inline, stylesheet: scopeCss(leftover.join('',), scope,), };
}

/** `{ a: '1', b: '2' }` → `a:1;b:2`. */
function serialize(decls: Record<string, string>,): string {
    return Object.entries(decls,).map(([k, v,],) => `${k}:${v}`).join(';',);
}

/** An element the scan currently has open. */
interface OpenTag {
    tag: string;
    attrs: string;
}

/** Read an attribute's value out of an opening tag's attribute text. */
function attr(attrs: string, name: string,): string {
    const re = new RegExp(`\\s${name}\\s*=\\s*("([^"]*)"|'([^']*)'|([^\\s>]+))`, 'i',);
    const m = re.exec(attrs,);
    return m?.[2] ?? m?.[3] ?? m?.[4] ?? '';
}

/** Does this opening tag satisfy one compound? */
function compoundMatches(el: OpenTag, c: Compound,): boolean {
    if (c.tag && c.tag !== el.tag) return false;
    if (c.classes.length) {
        const classes = attr(el.attrs, 'class',).split(/\s+/,);
        if (!c.classes.every(cls => classes.includes(cls,))) return false;
    }
    if (c.id && attr(el.attrs, 'id',) !== c.id) return false;
    return true;
}

/**
 * Does `el`, sitting under `stack` (outermost first), satisfy the chain?
 *
 * Walks the ancestors innermost-first — the same direction a browser matches —
 * so a `child` step checks only the immediately enclosing element while a
 * `descendant` step scans outward for the first match.
 */
function matchesChain(el: OpenTag, stack: OpenTag[], chain: SelectorChain,): boolean {
    if (!compoundMatches(el, chain.subject,)) return false;
    let i = stack.length - 1; // innermost ancestor
    for (const step of chain.ancestors) {
        if (step.combinator === 'child') {
            if (i < 0 || !compoundMatches(stack[i], step.compound,)) return false;
            i -= 1;
            continue;
        }
        while (i >= 0 && !compoundMatches(stack[i], step.compound,)) i -= 1;
        if (i < 0) return false;
        i -= 1;
    }
    return true;
}

/** HTML elements that never have children, so they never enter the stack. */
const VOID_ELEMENTS = new Set([
    'area',
    'base',
    'br',
    'col',
    'embed',
    'hr',
    'img',
    'input',
    'link',
    'meta',
    'param',
    'source',
    'track',
    'wbr',
],);

/** Opening tag, closing tag, comment, or declaration. */
const TAG = /<(\/)?([a-z][\w-]*)((?:[^>"']|"[^"]*"|'[^']*')*)>|<!--[\s\S]*?-->/gi;

/** Merge declarations into an opening tag's `style` attribute. */
function withStyle(tag: string, attrs: string, decls: Record<string, string>,): string {
    const styleRe = /\sstyle\s*=\s*("([^"]*)"|'([^']*)')/i;
    const existing = styleRe.exec(attrs,);
    if (existing) {
        const prior = parseDeclarations(existing[2] ?? existing[3] ?? '',);
        const next = serialize({ ...prior, ...decls, },);
        return `<${tag}${attrs.replace(styleRe, ` style="${next}"`,)}>`;
    }
    // A self-closing tag keeps its slash; appending after it would produce
    // `<br/ style="…">`. Trailing space is trimmed with it, or the reinserted
    // separator doubles up (`<img src="x" <space><space> style=…`).
    const selfClosing = attrs.endsWith('/',);
    const base = selfClosing ? attrs.slice(0, -1,).replace(/\s+$/, '',) : attrs;
    return `<${tag}${base} style="${serialize(decls,)}"${selfClosing ? ' /' : ''}>`;
}

/**
 * Write the matching rules' declarations onto every matching element in `html`.
 *
 * Scans tags in order while maintaining the stack of currently-open elements,
 * so a selector's ancestor steps can be checked against real structure rather
 * than guessed at. That stack is trustworthy precisely because this markup is
 * generated by the renderers next door — it is well formed by construction,
 * which is what makes `td a img` answerable without a DOM.
 *
 * Operator declarations are merged AFTER any style attribute already present,
 * so they win — an operator reaches for Custom CSS precisely when what the
 * renderer produced is not what they want. This is a small divergence from the
 * web, where an author's own inline style (from the rich-text editor) would
 * beat a stylesheet; in email every style is inline, so honouring that would
 * mean the field could never change anything a renderer had emitted.
 */
export function applyInlineRules(html: string, rules: InlineRule[],): string {
    if (!rules.length || !html) return html;

    const stack: OpenTag[] = [];
    let out = '';
    let last = 0;
    TAG.lastIndex = 0;

    for (let m = TAG.exec(html,); m; m = TAG.exec(html,)) {
        const [whole, closing, rawTag, rawAttrs,] = m;
        out += html.slice(last, m.index,);
        last = m.index + whole.length;

        // A comment matches neither branch of the pattern's alternation.
        if (rawTag === undefined) {
            out += whole;
            continue;
        }
        const tag = rawTag.toLowerCase();
        const attrs = rawAttrs ?? '';

        if (closing) {
            // Pop to the matching open tag. Tolerant of unclosed elements:
            // leaving the stack untouched on a stray `</div>` is safer than
            // clearing it, which would drop every ancestor of what follows.
            const at = stack.map(e => e.tag).lastIndexOf(tag,);
            if (at >= 0) stack.length = at;
            out += whole;
            continue;
        }

        const el: OpenTag = { tag, attrs, };
        const merged: Record<string, string> = {};
        for (const r of rules) if (matchesChain(el, stack, r.match,)) Object.assign(merged, r.decls,);
        out += Object.keys(merged,).length ? withStyle(rawTag, attrs, merged,) : whole;

        if (!VOID_ELEMENTS.has(tag,) && !attrs.endsWith('/',)) stack.push(el,);
    }

    return out + html.slice(last,);
}

/**
 * Turn a scoped stylesheet into `<style>`-ready rules whose declarations beat
 * the inline styles on the same elements.
 *
 * `!important` is the only lever available here. Email has no cascade layers,
 * and every base style in this renderer is an inline attribute, which outranks
 * any stylesheet rule without it. (The web path must NOT do this — there the
 * layers provide precedence and `!important` would break template overrides.)
 */
export function importantify(sheet: string,): string {
    return sheet.replace(/\{([^{}]*)\}/g, (whole, body: string,) => {
        const decls = parseDeclarations(body,);
        const keys = Object.keys(decls,);
        if (!keys.length) return whole;
        return `{${keys.map(k => `${k}:${decls[k]} !important`).join(';',)}}`;
    },);
}
