/**
 * A block's operator-authored Custom CSS, translated for email.
 *
 * On the web the whole sheet is scoped and injected as a `<style>`. Email has
 * no such luxury: Gmail strips `<style>` in a forwarded message, several
 * clients drop it outright, and Outlook's Word engine ignores most of what
 * survives. Inline `style` attributes are the only thing that works
 * everywhere — which is why every other part of this renderer is inline.
 *
 * So the sheet is SPLIT by how reliably each rule can be delivered:
 *
 *   1. `&` and bare declarations → merged into the block's own `<td>` style.
 *      Completely reliable, and the shape most operators actually write.
 *   2. Tag / class / id compounds joined by descendant (` `) or child (`>`)
 *      combinators — `p`, `.price`, `a.btn`, `td a img`, `div > p` → inlined
 *      onto every matching element in the block's own markup.
 *   3. Everything else — pseudo-classes, attribute selectors, sibling
 *      combinators, media queries — → the head `<style>`, scoped to this
 *      block. A progressive enhancement, exactly like the per-breakpoint rules
 *      next door, and not honoured by every client.
 *
 * Why group 2 can include combinators without a DOM: `applyInlineRules` scans
 * the markup in order and keeps the stack of currently-open elements, so an
 * ancestor step is answered from real structure. That stack is trustworthy
 * because this HTML is generated by the renderers next door — it is well
 * formed by construction.
 *
 * Group 3 is where certainty runs out rather than where effort did. A sibling
 * combinator needs elements the scan has already closed and discarded; a
 * pseudo-class has no inline equivalent at all. Guessing at those would
 * silently corrupt the messages it got wrong, which is worse than a rule that
 * plainly does or does not arrive.
 *
 * Precedence: the operator's declarations are merged LAST, so they beat what
 * this renderer emitted. That mirrors the web, where custom CSS closes the
 * block's cascade layer and overrides the style controls above it.
 */
import { parseCssRules, parseDeclarations, scopeCss, } from '@sitesurge/types';
import { parseSelectorChain, } from './cssSelectors';
import { applyInlineRules, type InlineRule, } from './htmlInliner';

/*
 * Re-exported so `planCustomCss`'s callers and tests reach the whole feature
 * through one module, even though it is now assembled from three.
 */
export { applyInlineRules, type InlineRule, };
export { parseDeclarations, };

export interface EmailCustomCss {
    /** Declarations for the block's own cell. */
    cell: Record<string, string>;
    /** Rules to inline onto elements inside the block's markup. */
    inline: InlineRule[];
    /** Rules that could not be inlined, already scoped to this block. */
    stylesheet: string;
}

const EMPTY: EmailCustomCss = { cell: {}, inline: [], stylesheet: '', };

/**
 * Classify one block's custom CSS into the three delivery groups.
 *
 * `scope` is the selector the leftover stylesheet is scoped to — for email,
 * `[data-block-id="…"]` (there is no `.block` wrapper in a table layout).
 */
export function planCustomCss(css: string | null | undefined, scope: string,): EmailCustomCss {
    if (!css || !css.trim()) return EMPTY;

    const cell: Record<string, string> = {};
    const inline: InlineRule[] = [];
    const leftover: string[] = [];

    for (const rule of parseCssRules(css,)) {
        if (rule.atRule) {
            // A media/supports query cannot be inlined by definition — an
            // inline style has no condition attached to it.
            leftover.push(`${rule.selector}{${rule.body}}`,);
            continue;
        }
        const decls = parseDeclarations(rule.body,);
        // Selector-less declarations mean "this block".
        if (!rule.selector) {
            Object.assign(cell, decls,);
            continue;
        }
        for (const one of rule.selector.split(',',).map(s => s.trim()).filter(Boolean,)) {
            if (one === '&') {
                Object.assign(cell, decls,);
                continue;
            }
            const chain = parseSelectorChain(one,);
            if (chain && Object.keys(decls,).length) inline.push({ match: chain, decls, },);
            else leftover.push(`${one}{${rule.body}}`,);
        }
    }

    return { cell, inline, stylesheet: scopeCss(leftover.join('',), scope,), };
}

/**
 * Turn a scoped stylesheet into `<style>`-ready rules whose declarations beat
 * the inline styles on the same elements.
 *
 * `!important` is the only lever available here. Email has no cascade layers,
 * and every base style in this renderer is an inline attribute, which outranks
 * any stylesheet rule without it. (The web path must NOT do this — there the
 * layers provide precedence and `!important` would break template overrides.)
 */
export function importantify(sheet: string,): string {
    return sheet.replace(/\{([^{}]*)\}/g, (whole, body: string,) => {
        const decls = parseDeclarations(body,);
        const keys = Object.keys(decls,);
        if (!keys.length) return whole;
        return `{${keys.map(k => `${k}:${decls[k]} !important`).join(';',)}}`;
    },);
}
