/**
 * Apply CSS rules to an HTML string by scanning it, with no DOM.
 *
 * Split out of `customCss.ts`. This half knows nothing about email — it is a
 * small selector engine: walk the tags in order, keep the stack of currently
 * open elements, and merge declarations onto the ones that match.
 *
 * The stack is what makes ancestor steps (`td a img`, `div > p`) answerable
 * without a parser, and it is trustworthy only because the markup it runs on is
 * GENERATED by the renderers beside it — well formed by construction. Pointed
 * at arbitrary HTML it would be best-effort.
 */
import { parseDeclarations, } from '@sitesurge/types';
import type { Compound, SelectorChain, } from './cssSelectors';

/** A selector chain plus the declarations to apply where it matches. */
export interface InlineRule {
    match: SelectorChain;
    decls: Record<string, string>;
}

/** `{ a: '1', b: '2' }` → `a:1;b:2`. */
function serialize(decls: Record<string, string>,): string {
    return Object.entries(decls,).map(([k, v,],) => `${k}:${v}`).join(';',);
}

/** An element the scan currently has open. */
interface OpenTag {
    tag: string;
    attrs: string;
}

/** Read an attribute's value out of an opening tag's attribute text. */
function attr(attrs: string, name: string,): string {
    const re = new RegExp(`\\s${name}\\s*=\\s*("([^"]*)"|'([^']*)'|([^\\s>]+))`, 'i',);
    const m = re.exec(attrs,);
    return m?.[2] ?? m?.[3] ?? m?.[4] ?? '';
}

/** Does this opening tag satisfy one compound? */
function compoundMatches(el: OpenTag, c: Compound,): boolean {
    if (c.tag && c.tag !== el.tag) return false;
    if (c.classes.length) {
        const classes = attr(el.attrs, 'class',).split(/\s+/,);
        if (!c.classes.every(cls => classes.includes(cls,))) return false;
    }
    if (c.id && attr(el.attrs, 'id',) !== c.id) return false;
    return true;
}

/**
 * Does `el`, sitting under `stack` (outermost first), satisfy the chain?
 *
 * Walks the ancestors innermost-first — the same direction a browser matches —
 * so a `child` step checks only the immediately enclosing element while a
 * `descendant` step scans outward for the first match.
 */
function matchesChain(el: OpenTag, stack: OpenTag[], chain: SelectorChain,): boolean {
    if (!compoundMatches(el, chain.subject,)) return false;
    let i = stack.length - 1; // innermost ancestor
    for (const step of chain.ancestors) {
        if (step.combinator === 'child') {
            if (i < 0 || !compoundMatches(stack[i], step.compound,)) return false;
            i -= 1;
            continue;
        }
        while (i >= 0 && !compoundMatches(stack[i], step.compound,)) i -= 1;
        if (i < 0) return false;
        i -= 1;
    }
    return true;
}

/** HTML elements that never have children, so they never enter the stack. */
const VOID_ELEMENTS = new Set([
    'area',
    'base',
    'br',
    'col',
    'embed',
    'hr',
    'img',
    'input',
    'link',
    'meta',
    'param',
    'source',
    'track',
    'wbr',
],);

/** Opening tag, closing tag, comment, or declaration. */
const TAG = /<(\/)?([a-z][\w-]*)((?:[^>"']|"[^"]*"|'[^']*')*)>|<!--[\s\S]*?-->/gi;

/** Merge declarations into an opening tag's `style` attribute. */
function withStyle(tag: string, attrs: string, decls: Record<string, string>,): string {
    const styleRe = /\sstyle\s*=\s*("([^"]*)"|'([^']*)')/i;
    const existing = styleRe.exec(attrs,);
    if (existing) {
        const prior = parseDeclarations(existing[2] ?? existing[3] ?? '',);
        const next = serialize({ ...prior, ...decls, },);
        return `<${tag}${attrs.replace(styleRe, ` style="${next}"`,)}>`;
    }
    // A self-closing tag keeps its slash; appending after it would produce
    // `<br/ style="…">`. Trailing space is trimmed with it, or the reinserted
    // separator doubles up (`<img src="x" <space><space> style=…`).
    const selfClosing = attrs.endsWith('/',);
    const base = selfClosing ? attrs.slice(0, -1,).replace(/\s+$/, '',) : attrs;
    return `<${tag}${base} style="${serialize(decls,)}"${selfClosing ? ' /' : ''}>`;
}

/**
 * Write the matching rules' declarations onto every matching element in `html`.
 *
 * Scans tags in order while maintaining the stack of currently-open elements,
 * so a selector's ancestor steps can be checked against real structure rather
 * than guessed at. That stack is trustworthy precisely because this markup is
 * generated by the renderers next door — it is well formed by construction,
 * which is what makes `td a img` answerable without a DOM.
 *
 * Operator declarations are merged AFTER any style attribute already present,
 * so they win — an operator reaches for Custom CSS precisely when what the
 * renderer produced is not what they want. This is a small divergence from the
 * web, where an author's own inline style (from the rich-text editor) would
 * beat a stylesheet; in email every style is inline, so honouring that would
 * mean the field could never change anything a renderer had emitted.
 */
export function applyInlineRules(html: string, rules: InlineRule[],): string {
    if (!rules.length || !html) return html;

    const stack: OpenTag[] = [];
    let out = '';
    let last = 0;
    TAG.lastIndex = 0;

    for (let m = TAG.exec(html,); m; m = TAG.exec(html,)) {
        const [whole, closing, rawTag, rawAttrs,] = m;
        out += html.slice(last, m.index,);
        last = m.index + whole.length;

        // A comment matches neither branch of the pattern's alternation.
        if (rawTag === undefined) {
            out += whole;
            continue;
        }
        const tag = rawTag.toLowerCase();
        const attrs = rawAttrs ?? '';

        if (closing) {
            // Pop to the matching open tag. Tolerant of unclosed elements:
            // leaving the stack untouched on a stray `</div>` is safer than
            // clearing it, which would drop every ancestor of what follows.
            const at = stack.map(e => e.tag).lastIndexOf(tag,);
            if (at >= 0) stack.length = at;
            out += whole;
            continue;
        }

        const el: OpenTag = { tag, attrs, };
        const merged: Record<string, string> = {};
        for (const r of rules) if (matchesChain(el, stack, r.match,)) Object.assign(merged, r.decls,);
        out += Object.keys(merged,).length ? withStyle(rawTag, attrs, merged,) : whole;

        if (!VOID_ELEMENTS.has(tag,) && !attrs.endsWith('/',)) stack.push(el,);
    }

    return out + html.slice(last,);
}
