/**
 * Static IANA time-zone list for time-zone dropdowns (e.g. the /profile + CRM
 * contact "Time zone" field). Generated from Node/ICU's
 * `Intl.supportedValuesOf("timeZone")` with standard-time (January) UTC offsets,
 * sorted west→east. Values are IANA ids (e.g. `America/New_York`); labels read
 * like `America - New York (GMT-5)`. Regenerate with
 * `node packages/shared/scripts/gen-timezones.mjs` (offsets are standard-time,
 * so DST is not reflected in the label).
 */
export interface TimeZoneOption {
    /** IANA time-zone id, e.g. `America/New_York`. */
    value: string;
    /** Human label, e.g. `America - New York (GMT-5)`. */
    label: string;
    /** Standard-time UTC offset in minutes (used for sorting; may differ under DST). */
    offsetMinutes: number;
}

export const TIMEZONES: TimeZoneOption[] = [
    { value: "Pacific/Midway", label: "Pacific - Midway (GMT-11)", offsetMinutes: -660, },
    { value: "Pacific/Niue", label: "Pacific - Niue (GMT-11)", offsetMinutes: -660, },
    { value: "Pacific/Pago_Pago", label: "Pacific - Pago Pago (GMT-11)", offsetMinutes: -660, },
    { value: "America/Adak", label: "America - Adak (GMT-10)", offsetMinutes: -600, },
    { value: "Pacific/Honolulu", label: "Pacific - Honolulu (GMT-10)", offsetMinutes: -600, },
    { value: "Pacific/Rarotonga", label: "Pacific - Rarotonga (GMT-10)", offsetMinutes: -600, },
    { value: "Pacific/Tahiti", label: "Pacific - Tahiti (GMT-10)", offsetMinutes: -600, },
    { value: "Pacific/Marquesas", label: "Pacific - Marquesas (GMT-9:30)", offsetMinutes: -570, },
    { value: "America/Anchorage", label: "America - Anchorage (GMT-9)", offsetMinutes: -540, },
    { value: "America/Juneau", label: "America - Juneau (GMT-9)", offsetMinutes: -540, },
    { value: "America/Metlakatla", label: "America - Metlakatla (GMT-9)", offsetMinutes: -540, },
    { value: "America/Nome", label: "America - Nome (GMT-9)", offsetMinutes: -540, },
    { value: "America/Sitka", label: "America - Sitka (GMT-9)", offsetMinutes: -540, },
    { value: "America/Yakutat", label: "America - Yakutat (GMT-9)", offsetMinutes: -540, },
    { value: "Pacific/Gambier", label: "Pacific - Gambier (GMT-9)", offsetMinutes: -540, },
    { value: "America/Los_Angeles", label: "America - Los Angeles (GMT-8)", offsetMinutes: -480, },
    { value: "America/Tijuana", label: "America - Tijuana (GMT-8)", offsetMinutes: -480, },
    { value: "America/Vancouver", label: "America - Vancouver (GMT-8)", offsetMinutes: -480, },
    { value: "Pacific/Pitcairn", label: "Pacific - Pitcairn (GMT-8)", offsetMinutes: -480, },
    { value: "America/Boise", label: "America - Boise (GMT-7)", offsetMinutes: -420, },
    { value: "America/Cambridge_Bay", label: "America - Cambridge Bay (GMT-7)", offsetMinutes: -420, },
    { value: "America/Ciudad_Juarez", label: "America - Ciudad Juarez (GMT-7)", offsetMinutes: -420, },
    { value: "America/Creston", label: "America - Creston (GMT-7)", offsetMinutes: -420, },
    { value: "America/Dawson", label: "America - Dawson (GMT-7)", offsetMinutes: -420, },
    { value: "America/Dawson_Creek", label: "America - Dawson Creek (GMT-7)", offsetMinutes: -420, },
    { value: "America/Denver", label: "America - Denver (GMT-7)", offsetMinutes: -420, },
    { value: "America/Edmonton", label: "America - Edmonton (GMT-7)", offsetMinutes: -420, },
    { value: "America/Fort_Nelson", label: "America - Fort Nelson (GMT-7)", offsetMinutes: -420, },
    { value: "America/Hermosillo", label: "America - Hermosillo (GMT-7)", offsetMinutes: -420, },
    { value: "America/Inuvik", label: "America - Inuvik (GMT-7)", offsetMinutes: -420, },
    { value: "America/Mazatlan", label: "America - Mazatlan (GMT-7)", offsetMinutes: -420, },
    { value: "America/Phoenix", label: "America - Phoenix (GMT-7)", offsetMinutes: -420, },
    { value: "America/Whitehorse", label: "America - Whitehorse (GMT-7)", offsetMinutes: -420, },
    { value: "America/Bahia_Banderas", label: "America - Bahia Banderas (GMT-6)", offsetMinutes: -360, },
    { value: "America/Belize", label: "America - Belize (GMT-6)", offsetMinutes: -360, },
    { value: "America/Chicago", label: "America - Chicago (GMT-6)", offsetMinutes: -360, },
    { value: "America/Chihuahua", label: "America - Chihuahua (GMT-6)", offsetMinutes: -360, },
    { value: "America/Costa_Rica", label: "America - Costa Rica (GMT-6)", offsetMinutes: -360, },
    { value: "America/El_Salvador", label: "America - El Salvador (GMT-6)", offsetMinutes: -360, },
    { value: "America/Guatemala", label: "America - Guatemala (GMT-6)", offsetMinutes: -360, },
    { value: "America/Indiana/Knox", label: "America - Indiana/Knox (GMT-6)", offsetMinutes: -360, },
    { value: "America/Indiana/Tell_City", label: "America - Indiana/Tell City (GMT-6)", offsetMinutes: -360, },
    { value: "America/Managua", label: "America - Managua (GMT-6)", offsetMinutes: -360, },
    { value: "America/Matamoros", label: "America - Matamoros (GMT-6)", offsetMinutes: -360, },
    { value: "America/Menominee", label: "America - Menominee (GMT-6)", offsetMinutes: -360, },
    { value: "America/Merida", label: "America - Merida (GMT-6)", offsetMinutes: -360, },
    { value: "America/Mexico_City", label: "America - Mexico City (GMT-6)", offsetMinutes: -360, },
    { value: "America/Monterrey", label: "America - Monterrey (GMT-6)", offsetMinutes: -360, },
    { value: "America/North_Dakota/Beulah", label: "America - North Dakota/Beulah (GMT-6)", offsetMinutes: -360, },
    { value: "America/North_Dakota/Center", label: "America - North Dakota/Center (GMT-6)", offsetMinutes: -360, },
    { value: "America/North_Dakota/New_Salem", label: "America - North Dakota/New Salem (GMT-6)", offsetMinutes: -360, },
    { value: "America/Ojinaga", label: "America - Ojinaga (GMT-6)", offsetMinutes: -360, },
    { value: "America/Rankin_Inlet", label: "America - Rankin Inlet (GMT-6)", offsetMinutes: -360, },
    { value: "America/Regina", label: "America - Regina (GMT-6)", offsetMinutes: -360, },
    { value: "America/Resolute", label: "America - Resolute (GMT-6)", offsetMinutes: -360, },
    { value: "America/Swift_Current", label: "America - Swift Current (GMT-6)", offsetMinutes: -360, },
    { value: "America/Tegucigalpa", label: "America - Tegucigalpa (GMT-6)", offsetMinutes: -360, },
    { value: "America/Winnipeg", label: "America - Winnipeg (GMT-6)", offsetMinutes: -360, },
    { value: "Pacific/Galapagos", label: "Pacific - Galapagos (GMT-6)", offsetMinutes: -360, },
    { value: "America/Bogota", label: "America - Bogota (GMT-5)", offsetMinutes: -300, },
    { value: "America/Cancun", label: "America - Cancun (GMT-5)", offsetMinutes: -300, },
    { value: "America/Cayman", label: "America - Cayman (GMT-5)", offsetMinutes: -300, },
    { value: "America/Coral_Harbour", label: "America - Coral Harbour (GMT-5)", offsetMinutes: -300, },
    { value: "America/Detroit", label: "America - Detroit (GMT-5)", offsetMinutes: -300, },
    { value: "America/Eirunepe", label: "America - Eirunepe (GMT-5)", offsetMinutes: -300, },
    { value: "America/Grand_Turk", label: "America - Grand Turk (GMT-5)", offsetMinutes: -300, },
    { value: "America/Guayaquil", label: "America - Guayaquil (GMT-5)", offsetMinutes: -300, },
    { value: "America/Havana", label: "America - Havana (GMT-5)", offsetMinutes: -300, },
    { value: "America/Indiana/Marengo", label: "America - Indiana/Marengo (GMT-5)", offsetMinutes: -300, },
    { value: "America/Indiana/Petersburg", label: "America - Indiana/Petersburg (GMT-5)", offsetMinutes: -300, },
    { value: "America/Indiana/Vevay", label: "America - Indiana/Vevay (GMT-5)", offsetMinutes: -300, },
    { value: "America/Indiana/Vincennes", label: "America - Indiana/Vincennes (GMT-5)", offsetMinutes: -300, },
    { value: "America/Indiana/Winamac", label: "America - Indiana/Winamac (GMT-5)", offsetMinutes: -300, },
    { value: "America/Indianapolis", label: "America - Indianapolis (GMT-5)", offsetMinutes: -300, },
    { value: "America/Iqaluit", label: "America - Iqaluit (GMT-5)", offsetMinutes: -300, },
    { value: "America/Jamaica", label: "America - Jamaica (GMT-5)", offsetMinutes: -300, },
    { value: "America/Kentucky/Monticello", label: "America - Kentucky/Monticello (GMT-5)", offsetMinutes: -300, },
    { value: "America/Lima", label: "America - Lima (GMT-5)", offsetMinutes: -300, },
    { value: "America/Louisville", label: "America - Louisville (GMT-5)", offsetMinutes: -300, },
    { value: "America/Nassau", label: "America - Nassau (GMT-5)", offsetMinutes: -300, },
    { value: "America/New_York", label: "America - New York (GMT-5)", offsetMinutes: -300, },
    { value: "America/Panama", label: "America - Panama (GMT-5)", offsetMinutes: -300, },
    { value: "America/Port-au-Prince", label: "America - Port-au-Prince (GMT-5)", offsetMinutes: -300, },
    { value: "America/Rio_Branco", label: "America - Rio Branco (GMT-5)", offsetMinutes: -300, },
    { value: "America/Toronto", label: "America - Toronto (GMT-5)", offsetMinutes: -300, },
    { value: "Pacific/Easter", label: "Pacific - Easter (GMT-5)", offsetMinutes: -300, },
    { value: "America/Anguilla", label: "America - Anguilla (GMT-4)", offsetMinutes: -240, },
    { value: "America/Antigua", label: "America - Antigua (GMT-4)", offsetMinutes: -240, },
    { value: "America/Aruba", label: "America - Aruba (GMT-4)", offsetMinutes: -240, },
    { value: "America/Barbados", label: "America - Barbados (GMT-4)", offsetMinutes: -240, },
    { value: "America/Blanc-Sablon", label: "America - Blanc-Sablon (GMT-4)", offsetMinutes: -240, },
    { value: "America/Boa_Vista", label: "America - Boa Vista (GMT-4)", offsetMinutes: -240, },
    { value: "America/Campo_Grande", label: "America - Campo Grande (GMT-4)", offsetMinutes: -240, },
    { value: "America/Caracas", label: "America - Caracas (GMT-4)", offsetMinutes: -240, },
    { value: "America/Cuiaba", label: "America - Cuiaba (GMT-4)", offsetMinutes: -240, },
    { value: "America/Curacao", label: "America - Curacao (GMT-4)", offsetMinutes: -240, },
    { value: "America/Dominica", label: "America - Dominica (GMT-4)", offsetMinutes: -240, },
    { value: "America/Glace_Bay", label: "America - Glace Bay (GMT-4)", offsetMinutes: -240, },
    { value: "America/Goose_Bay", label: "America - Goose Bay (GMT-4)", offsetMinutes: -240, },
    { value: "America/Grenada", label: "America - Grenada (GMT-4)", offsetMinutes: -240, },
    { value: "America/Guadeloupe", label: "America - Guadeloupe (GMT-4)", offsetMinutes: -240, },
    { value: "America/Guyana", label: "America - Guyana (GMT-4)", offsetMinutes: -240, },
    { value: "America/Halifax", label: "America - Halifax (GMT-4)", offsetMinutes: -240, },
    { value: "America/Kralendijk", label: "America - Kralendijk (GMT-4)", offsetMinutes: -240, },
    { value: "America/La_Paz", label: "America - La Paz (GMT-4)", offsetMinutes: -240, },
    { value: "America/Lower_Princes", label: "America - Lower Princes (GMT-4)", offsetMinutes: -240, },
    { value: "America/Manaus", label: "America - Manaus (GMT-4)", offsetMinutes: -240, },
    { value: "America/Marigot", label: "America - Marigot (GMT-4)", offsetMinutes: -240, },
    { value: "America/Martinique", label: "America - Martinique (GMT-4)", offsetMinutes: -240, },
    { value: "America/Moncton", label: "America - Moncton (GMT-4)", offsetMinutes: -240, },
    { value: "America/Montserrat", label: "America - Montserrat (GMT-4)", offsetMinutes: -240, },
    { value: "America/Port_of_Spain", label: "America - Port of Spain (GMT-4)", offsetMinutes: -240, },
    { value: "America/Porto_Velho", label: "America - Porto Velho (GMT-4)", offsetMinutes: -240, },
    { value: "America/Puerto_Rico", label: "America - Puerto Rico (GMT-4)", offsetMinutes: -240, },
    { value: "America/Santo_Domingo", label: "America - Santo Domingo (GMT-4)", offsetMinutes: -240, },
    { value: "America/St_Barthelemy", label: "America - St Barthelemy (GMT-4)", offsetMinutes: -240, },
    { value: "America/St_Kitts", label: "America - St Kitts (GMT-4)", offsetMinutes: -240, },
    { value: "America/St_Lucia", label: "America - St Lucia (GMT-4)", offsetMinutes: -240, },
    { value: "America/St_Thomas", label: "America - St Thomas (GMT-4)", offsetMinutes: -240, },
    { value: "America/St_Vincent", label: "America - St Vincent (GMT-4)", offsetMinutes: -240, },
    { value: "America/Thule", label: "America - Thule (GMT-4)", offsetMinutes: -240, },
    { value: "America/Tortola", label: "America - Tortola (GMT-4)", offsetMinutes: -240, },
    { value: "Atlantic/Bermuda", label: "Atlantic - Bermuda (GMT-4)", offsetMinutes: -240, },
    { value: "America/St_Johns", label: "America - St Johns (GMT-3:30)", offsetMinutes: -210, },
    { value: "America/Araguaina", label: "America - Araguaina (GMT-3)", offsetMinutes: -180, },
    { value: "America/Argentina/La_Rioja", label: "America - Argentina/La Rioja (GMT-3)", offsetMinutes: -180, },
    { value: "America/Argentina/Rio_Gallegos", label: "America - Argentina/Rio Gallegos (GMT-3)", offsetMinutes: -180, },
    { value: "America/Argentina/Salta", label: "America - Argentina/Salta (GMT-3)", offsetMinutes: -180, },
    { value: "America/Argentina/San_Juan", label: "America - Argentina/San Juan (GMT-3)", offsetMinutes: -180, },
    { value: "America/Argentina/San_Luis", label: "America - Argentina/San Luis (GMT-3)", offsetMinutes: -180, },
    { value: "America/Argentina/Tucuman", label: "America - Argentina/Tucuman (GMT-3)", offsetMinutes: -180, },
    { value: "America/Argentina/Ushuaia", label: "America - Argentina/Ushuaia (GMT-3)", offsetMinutes: -180, },
    { value: "America/Asuncion", label: "America - Asuncion (GMT-3)", offsetMinutes: -180, },
    { value: "America/Bahia", label: "America - Bahia (GMT-3)", offsetMinutes: -180, },
    { value: "America/Belem", label: "America - Belem (GMT-3)", offsetMinutes: -180, },
    { value: "America/Buenos_Aires", label: "America - Buenos Aires (GMT-3)", offsetMinutes: -180, },
    { value: "America/Catamarca", label: "America - Catamarca (GMT-3)", offsetMinutes: -180, },
    { value: "America/Cayenne", label: "America - Cayenne (GMT-3)", offsetMinutes: -180, },
    { value: "America/Cordoba", label: "America - Cordoba (GMT-3)", offsetMinutes: -180, },
    { value: "America/Coyhaique", label: "America - Coyhaique (GMT-3)", offsetMinutes: -180, },
    { value: "America/Fortaleza", label: "America - Fortaleza (GMT-3)", offsetMinutes: -180, },
    { value: "America/Jujuy", label: "America - Jujuy (GMT-3)", offsetMinutes: -180, },
    { value: "America/Maceio", label: "America - Maceio (GMT-3)", offsetMinutes: -180, },
    { value: "America/Mendoza", label: "America - Mendoza (GMT-3)", offsetMinutes: -180, },
    { value: "America/Miquelon", label: "America - Miquelon (GMT-3)", offsetMinutes: -180, },
    { value: "America/Montevideo", label: "America - Montevideo (GMT-3)", offsetMinutes: -180, },
    { value: "America/Paramaribo", label: "America - Paramaribo (GMT-3)", offsetMinutes: -180, },
    { value: "America/Punta_Arenas", label: "America - Punta Arenas (GMT-3)", offsetMinutes: -180, },
    { value: "America/Recife", label: "America - Recife (GMT-3)", offsetMinutes: -180, },
    { value: "America/Santarem", label: "America - Santarem (GMT-3)", offsetMinutes: -180, },
    { value: "America/Santiago", label: "America - Santiago (GMT-3)", offsetMinutes: -180, },
    { value: "America/Sao_Paulo", label: "America - Sao Paulo (GMT-3)", offsetMinutes: -180, },
    { value: "Antarctica/Palmer", label: "Antarctica - Palmer (GMT-3)", offsetMinutes: -180, },
    { value: "Antarctica/Rothera", label: "Antarctica - Rothera (GMT-3)", offsetMinutes: -180, },
    { value: "Atlantic/Stanley", label: "Atlantic - Stanley (GMT-3)", offsetMinutes: -180, },
    { value: "America/Godthab", label: "America - Godthab (GMT-2)", offsetMinutes: -120, },
    { value: "America/Noronha", label: "America - Noronha (GMT-2)", offsetMinutes: -120, },
    { value: "America/Scoresbysund", label: "America - Scoresbysund (GMT-2)", offsetMinutes: -120, },
    { value: "Atlantic/South_Georgia", label: "Atlantic - South Georgia (GMT-2)", offsetMinutes: -120, },
    { value: "Atlantic/Azores", label: "Atlantic - Azores (GMT-1)", offsetMinutes: -60, },
    { value: "Atlantic/Cape_Verde", label: "Atlantic - Cape Verde (GMT-1)", offsetMinutes: -60, },
    { value: "Africa/Abidjan", label: "Africa - Abidjan (GMT)", offsetMinutes: 0, },
    { value: "Africa/Accra", label: "Africa - Accra (GMT)", offsetMinutes: 0, },
    { value: "Africa/Bamako", label: "Africa - Bamako (GMT)", offsetMinutes: 0, },
    { value: "Africa/Banjul", label: "Africa - Banjul (GMT)", offsetMinutes: 0, },
    { value: "Africa/Bissau", label: "Africa - Bissau (GMT)", offsetMinutes: 0, },
    { value: "Africa/Conakry", label: "Africa - Conakry (GMT)", offsetMinutes: 0, },
    { value: "Africa/Dakar", label: "Africa - Dakar (GMT)", offsetMinutes: 0, },
    { value: "Africa/Freetown", label: "Africa - Freetown (GMT)", offsetMinutes: 0, },
    { value: "Africa/Lome", label: "Africa - Lome (GMT)", offsetMinutes: 0, },
    { value: "Africa/Monrovia", label: "Africa - Monrovia (GMT)", offsetMinutes: 0, },
    { value: "Africa/Nouakchott", label: "Africa - Nouakchott (GMT)", offsetMinutes: 0, },
    { value: "Africa/Ouagadougou", label: "Africa - Ouagadougou (GMT)", offsetMinutes: 0, },
    { value: "Africa/Sao_Tome", label: "Africa - Sao Tome (GMT)", offsetMinutes: 0, },
    { value: "America/Danmarkshavn", label: "America - Danmarkshavn (GMT)", offsetMinutes: 0, },
    { value: "Antarctica/Troll", label: "Antarctica - Troll (GMT)", offsetMinutes: 0, },
    { value: "Atlantic/Canary", label: "Atlantic - Canary (GMT)", offsetMinutes: 0, },
    { value: "Atlantic/Faeroe", label: "Atlantic - Faeroe (GMT)", offsetMinutes: 0, },
    { value: "Atlantic/Madeira", label: "Atlantic - Madeira (GMT)", offsetMinutes: 0, },
    { value: "Atlantic/Reykjavik", label: "Atlantic - Reykjavik (GMT)", offsetMinutes: 0, },
    { value: "Atlantic/St_Helena", label: "Atlantic - St Helena (GMT)", offsetMinutes: 0, },
    { value: "Europe/Dublin", label: "Europe - Dublin (GMT)", offsetMinutes: 0, },
    { value: "Europe/Guernsey", label: "Europe - Guernsey (GMT)", offsetMinutes: 0, },
    { value: "Europe/Isle_of_Man", label: "Europe - Isle of Man (GMT)", offsetMinutes: 0, },
    { value: "Europe/Jersey", label: "Europe - Jersey (GMT)", offsetMinutes: 0, },
    { value: "Europe/Lisbon", label: "Europe - Lisbon (GMT)", offsetMinutes: 0, },
    { value: "Europe/London", label: "Europe - London (GMT)", offsetMinutes: 0, },
    { value: "Africa/Algiers", label: "Africa - Algiers (GMT+1)", offsetMinutes: 60, },
    { value: "Africa/Bangui", label: "Africa - Bangui (GMT+1)", offsetMinutes: 60, },
    { value: "Africa/Brazzaville", label: "Africa - Brazzaville (GMT+1)", offsetMinutes: 60, },
    { value: "Africa/Casablanca", label: "Africa - Casablanca (GMT+1)", offsetMinutes: 60, },
    { value: "Africa/Ceuta", label: "Africa - Ceuta (GMT+1)", offsetMinutes: 60, },
    { value: "Africa/Douala", label: "Africa - Douala (GMT+1)", offsetMinutes: 60, },
    { value: "Africa/El_Aaiun", label: "Africa - El Aaiun (GMT+1)", offsetMinutes: 60, },
    { value: "Africa/Kinshasa", label: "Africa - Kinshasa (GMT+1)", offsetMinutes: 60, },
    { value: "Africa/Lagos", label: "Africa - Lagos (GMT+1)", offsetMinutes: 60, },
    { value: "Africa/Libreville", label: "Africa - Libreville (GMT+1)", offsetMinutes: 60, },
    { value: "Africa/Luanda", label: "Africa - Luanda (GMT+1)", offsetMinutes: 60, },
    { value: "Africa/Malabo", label: "Africa - Malabo (GMT+1)", offsetMinutes: 60, },
    { value: "Africa/Ndjamena", label: "Africa - Ndjamena (GMT+1)", offsetMinutes: 60, },
    { value: "Africa/Niamey", label: "Africa - Niamey (GMT+1)", offsetMinutes: 60, },
    { value: "Africa/Porto-Novo", label: "Africa - Porto-Novo (GMT+1)", offsetMinutes: 60, },
    { value: "Africa/Tunis", label: "Africa - Tunis (GMT+1)", offsetMinutes: 60, },
    { value: "Arctic/Longyearbyen", label: "Arctic - Longyearbyen (GMT+1)", offsetMinutes: 60, },
    { value: "Europe/Amsterdam", label: "Europe - Amsterdam (GMT+1)", offsetMinutes: 60, },
    { value: "Europe/Andorra", label: "Europe - Andorra (GMT+1)", offsetMinutes: 60, },
    { value: "Europe/Belgrade", label: "Europe - Belgrade (GMT+1)", offsetMinutes: 60, },
    { value: "Europe/Berlin", label: "Europe - Berlin (GMT+1)", offsetMinutes: 60, },
    { value: "Europe/Bratislava", label: "Europe - Bratislava (GMT+1)", offsetMinutes: 60, },
    { value: "Europe/Brussels", label: "Europe - Brussels (GMT+1)", offsetMinutes: 60, },
    { value: "Europe/Budapest", label: "Europe - Budapest (GMT+1)", offsetMinutes: 60, },
    { value: "Europe/Busingen", label: "Europe - Busingen (GMT+1)", offsetMinutes: 60, },
    { value: "Europe/Copenhagen", label: "Europe - Copenhagen (GMT+1)", offsetMinutes: 60, },
    { value: "Europe/Gibraltar", label: "Europe - Gibraltar (GMT+1)", offsetMinutes: 60, },
    { value: "Europe/Ljubljana", label: "Europe - Ljubljana (GMT+1)", offsetMinutes: 60, },
    { value: "Europe/Luxembourg", label: "Europe - Luxembourg (GMT+1)", offsetMinutes: 60, },
    { value: "Europe/Madrid", label: "Europe - Madrid (GMT+1)", offsetMinutes: 60, },
    { value: "Europe/Malta", label: "Europe - Malta (GMT+1)", offsetMinutes: 60, },
    { value: "Europe/Monaco", label: "Europe - Monaco (GMT+1)", offsetMinutes: 60, },
    { value: "Europe/Oslo", label: "Europe - Oslo (GMT+1)", offsetMinutes: 60, },
    { value: "Europe/Paris", label: "Europe - Paris (GMT+1)", offsetMinutes: 60, },
    { value: "Europe/Podgorica", label: "Europe - Podgorica (GMT+1)", offsetMinutes: 60, },
    { value: "Europe/Prague", label: "Europe - Prague (GMT+1)", offsetMinutes: 60, },
    { value: "Europe/Rome", label: "Europe - Rome (GMT+1)", offsetMinutes: 60, },
    { value: "Europe/San_Marino", label: "Europe - San Marino (GMT+1)", offsetMinutes: 60, },
    { value: "Europe/Sarajevo", label: "Europe - Sarajevo (GMT+1)", offsetMinutes: 60, },
    { value: "Europe/Skopje", label: "Europe - Skopje (GMT+1)", offsetMinutes: 60, },
    { value: "Europe/Stockholm", label: "Europe - Stockholm (GMT+1)", offsetMinutes: 60, },
    { value: "Europe/Tirane", label: "Europe - Tirane (GMT+1)", offsetMinutes: 60, },
    { value: "Europe/Vaduz", label: "Europe - Vaduz (GMT+1)", offsetMinutes: 60, },
    { value: "Europe/Vatican", label: "Europe - Vatican (GMT+1)", offsetMinutes: 60, },
    { value: "Europe/Vienna", label: "Europe - Vienna (GMT+1)", offsetMinutes: 60, },
    { value: "Europe/Warsaw", label: "Europe - Warsaw (GMT+1)", offsetMinutes: 60, },
    { value: "Europe/Zagreb", label: "Europe - Zagreb (GMT+1)", offsetMinutes: 60, },
    { value: "Europe/Zurich", label: "Europe - Zurich (GMT+1)", offsetMinutes: 60, },
    { value: "Africa/Blantyre", label: "Africa - Blantyre (GMT+2)", offsetMinutes: 120, },
    { value: "Africa/Bujumbura", label: "Africa - Bujumbura (GMT+2)", offsetMinutes: 120, },
    { value: "Africa/Cairo", label: "Africa - Cairo (GMT+2)", offsetMinutes: 120, },
    { value: "Africa/Gaborone", label: "Africa - Gaborone (GMT+2)", offsetMinutes: 120, },
    { value: "Africa/Harare", label: "Africa - Harare (GMT+2)", offsetMinutes: 120, },
    { value: "Africa/Johannesburg", label: "Africa - Johannesburg (GMT+2)", offsetMinutes: 120, },
    { value: "Africa/Juba", label: "Africa - Juba (GMT+2)", offsetMinutes: 120, },
    { value: "Africa/Khartoum", label: "Africa - Khartoum (GMT+2)", offsetMinutes: 120, },
    { value: "Africa/Kigali", label: "Africa - Kigali (GMT+2)", offsetMinutes: 120, },
    { value: "Africa/Lubumbashi", label: "Africa - Lubumbashi (GMT+2)", offsetMinutes: 120, },
    { value: "Africa/Lusaka", label: "Africa - Lusaka (GMT+2)", offsetMinutes: 120, },
    { value: "Africa/Maputo", label: "Africa - Maputo (GMT+2)", offsetMinutes: 120, },
    { value: "Africa/Maseru", label: "Africa - Maseru (GMT+2)", offsetMinutes: 120, },
    { value: "Africa/Mbabane", label: "Africa - Mbabane (GMT+2)", offsetMinutes: 120, },
    { value: "Africa/Tripoli", label: "Africa - Tripoli (GMT+2)", offsetMinutes: 120, },
    { value: "Africa/Windhoek", label: "Africa - Windhoek (GMT+2)", offsetMinutes: 120, },
    { value: "Asia/Beirut", label: "Asia - Beirut (GMT+2)", offsetMinutes: 120, },
    { value: "Asia/Famagusta", label: "Asia - Famagusta (GMT+2)", offsetMinutes: 120, },
    { value: "Asia/Gaza", label: "Asia - Gaza (GMT+2)", offsetMinutes: 120, },
    { value: "Asia/Hebron", label: "Asia - Hebron (GMT+2)", offsetMinutes: 120, },
    { value: "Asia/Jerusalem", label: "Asia - Jerusalem (GMT+2)", offsetMinutes: 120, },
    { value: "Asia/Nicosia", label: "Asia - Nicosia (GMT+2)", offsetMinutes: 120, },
    { value: "Europe/Athens", label: "Europe - Athens (GMT+2)", offsetMinutes: 120, },
    { value: "Europe/Bucharest", label: "Europe - Bucharest (GMT+2)", offsetMinutes: 120, },
    { value: "Europe/Chisinau", label: "Europe - Chisinau (GMT+2)", offsetMinutes: 120, },
    { value: "Europe/Helsinki", label: "Europe - Helsinki (GMT+2)", offsetMinutes: 120, },
    { value: "Europe/Kaliningrad", label: "Europe - Kaliningrad (GMT+2)", offsetMinutes: 120, },
    { value: "Europe/Kiev", label: "Europe - Kiev (GMT+2)", offsetMinutes: 120, },
    { value: "Europe/Mariehamn", label: "Europe - Mariehamn (GMT+2)", offsetMinutes: 120, },
    { value: "Europe/Riga", label: "Europe - Riga (GMT+2)", offsetMinutes: 120, },
    { value: "Europe/Sofia", label: "Europe - Sofia (GMT+2)", offsetMinutes: 120, },
    { value: "Europe/Tallinn", label: "Europe - Tallinn (GMT+2)", offsetMinutes: 120, },
    { value: "Europe/Vilnius", label: "Europe - Vilnius (GMT+2)", offsetMinutes: 120, },
    { value: "Africa/Addis_Ababa", label: "Africa - Addis Ababa (GMT+3)", offsetMinutes: 180, },
    { value: "Africa/Asmera", label: "Africa - Asmera (GMT+3)", offsetMinutes: 180, },
    { value: "Africa/Dar_es_Salaam", label: "Africa - Dar es Salaam (GMT+3)", offsetMinutes: 180, },
    { value: "Africa/Djibouti", label: "Africa - Djibouti (GMT+3)", offsetMinutes: 180, },
    { value: "Africa/Kampala", label: "Africa - Kampala (GMT+3)", offsetMinutes: 180, },
    { value: "Africa/Mogadishu", label: "Africa - Mogadishu (GMT+3)", offsetMinutes: 180, },
    { value: "Africa/Nairobi", label: "Africa - Nairobi (GMT+3)", offsetMinutes: 180, },
    { value: "Antarctica/Syowa", label: "Antarctica - Syowa (GMT+3)", offsetMinutes: 180, },
    { value: "Asia/Aden", label: "Asia - Aden (GMT+3)", offsetMinutes: 180, },
    { value: "Asia/Amman", label: "Asia - Amman (GMT+3)", offsetMinutes: 180, },
    { value: "Asia/Baghdad", label: "Asia - Baghdad (GMT+3)", offsetMinutes: 180, },
    { value: "Asia/Bahrain", label: "Asia - Bahrain (GMT+3)", offsetMinutes: 180, },
    { value: "Asia/Damascus", label: "Asia - Damascus (GMT+3)", offsetMinutes: 180, },
    { value: "Asia/Kuwait", label: "Asia - Kuwait (GMT+3)", offsetMinutes: 180, },
    { value: "Asia/Qatar", label: "Asia - Qatar (GMT+3)", offsetMinutes: 180, },
    { value: "Asia/Riyadh", label: "Asia - Riyadh (GMT+3)", offsetMinutes: 180, },
    { value: "Europe/Istanbul", label: "Europe - Istanbul (GMT+3)", offsetMinutes: 180, },
    { value: "Europe/Kirov", label: "Europe - Kirov (GMT+3)", offsetMinutes: 180, },
    { value: "Europe/Minsk", label: "Europe - Minsk (GMT+3)", offsetMinutes: 180, },
    { value: "Europe/Moscow", label: "Europe - Moscow (GMT+3)", offsetMinutes: 180, },
    { value: "Europe/Simferopol", label: "Europe - Simferopol (GMT+3)", offsetMinutes: 180, },
    { value: "Europe/Volgograd", label: "Europe - Volgograd (GMT+3)", offsetMinutes: 180, },
    { value: "Indian/Antananarivo", label: "Indian - Antananarivo (GMT+3)", offsetMinutes: 180, },
    { value: "Indian/Comoro", label: "Indian - Comoro (GMT+3)", offsetMinutes: 180, },
    { value: "Indian/Mayotte", label: "Indian - Mayotte (GMT+3)", offsetMinutes: 180, },
    { value: "Asia/Tehran", label: "Asia - Tehran (GMT+3:30)", offsetMinutes: 210, },
    { value: "Asia/Baku", label: "Asia - Baku (GMT+4)", offsetMinutes: 240, },
    { value: "Asia/Dubai", label: "Asia - Dubai (GMT+4)", offsetMinutes: 240, },
    { value: "Asia/Muscat", label: "Asia - Muscat (GMT+4)", offsetMinutes: 240, },
    { value: "Asia/Tbilisi", label: "Asia - Tbilisi (GMT+4)", offsetMinutes: 240, },
    { value: "Asia/Yerevan", label: "Asia - Yerevan (GMT+4)", offsetMinutes: 240, },
    { value: "Europe/Astrakhan", label: "Europe - Astrakhan (GMT+4)", offsetMinutes: 240, },
    { value: "Europe/Samara", label: "Europe - Samara (GMT+4)", offsetMinutes: 240, },
    { value: "Europe/Saratov", label: "Europe - Saratov (GMT+4)", offsetMinutes: 240, },
    { value: "Europe/Ulyanovsk", label: "Europe - Ulyanovsk (GMT+4)", offsetMinutes: 240, },
    { value: "Indian/Mahe", label: "Indian - Mahe (GMT+4)", offsetMinutes: 240, },
    { value: "Indian/Mauritius", label: "Indian - Mauritius (GMT+4)", offsetMinutes: 240, },
    { value: "Indian/Reunion", label: "Indian - Reunion (GMT+4)", offsetMinutes: 240, },
    { value: "Asia/Kabul", label: "Asia - Kabul (GMT+4:30)", offsetMinutes: 270, },
    { value: "Antarctica/Mawson", label: "Antarctica - Mawson (GMT+5)", offsetMinutes: 300, },
    { value: "Antarctica/Vostok", label: "Antarctica - Vostok (GMT+5)", offsetMinutes: 300, },
    { value: "Asia/Almaty", label: "Asia - Almaty (GMT+5)", offsetMinutes: 300, },
    { value: "Asia/Aqtau", label: "Asia - Aqtau (GMT+5)", offsetMinutes: 300, },
    { value: "Asia/Aqtobe", label: "Asia - Aqtobe (GMT+5)", offsetMinutes: 300, },
    { value: "Asia/Ashgabat", label: "Asia - Ashgabat (GMT+5)", offsetMinutes: 300, },
    { value: "Asia/Atyrau", label: "Asia - Atyrau (GMT+5)", offsetMinutes: 300, },
    { value: "Asia/Dushanbe", label: "Asia - Dushanbe (GMT+5)", offsetMinutes: 300, },
    { value: "Asia/Karachi", label: "Asia - Karachi (GMT+5)", offsetMinutes: 300, },
    { value: "Asia/Oral", label: "Asia - Oral (GMT+5)", offsetMinutes: 300, },
    { value: "Asia/Qostanay", label: "Asia - Qostanay (GMT+5)", offsetMinutes: 300, },
    { value: "Asia/Qyzylorda", label: "Asia - Qyzylorda (GMT+5)", offsetMinutes: 300, },
    { value: "Asia/Samarkand", label: "Asia - Samarkand (GMT+5)", offsetMinutes: 300, },
    { value: "Asia/Tashkent", label: "Asia - Tashkent (GMT+5)", offsetMinutes: 300, },
    { value: "Asia/Yekaterinburg", label: "Asia - Yekaterinburg (GMT+5)", offsetMinutes: 300, },
    { value: "Indian/Kerguelen", label: "Indian - Kerguelen (GMT+5)", offsetMinutes: 300, },
    { value: "Indian/Maldives", label: "Indian - Maldives (GMT+5)", offsetMinutes: 300, },
    { value: "Asia/Calcutta", label: "Asia - Calcutta (GMT+5:30)", offsetMinutes: 330, },
    { value: "Asia/Colombo", label: "Asia - Colombo (GMT+5:30)", offsetMinutes: 330, },
    { value: "Asia/Katmandu", label: "Asia - Katmandu (GMT+5:45)", offsetMinutes: 345, },
    { value: "Asia/Bishkek", label: "Asia - Bishkek (GMT+6)", offsetMinutes: 360, },
    { value: "Asia/Dhaka", label: "Asia - Dhaka (GMT+6)", offsetMinutes: 360, },
    { value: "Asia/Omsk", label: "Asia - Omsk (GMT+6)", offsetMinutes: 360, },
    { value: "Asia/Thimphu", label: "Asia - Thimphu (GMT+6)", offsetMinutes: 360, },
    { value: "Asia/Urumqi", label: "Asia - Urumqi (GMT+6)", offsetMinutes: 360, },
    { value: "Indian/Chagos", label: "Indian - Chagos (GMT+6)", offsetMinutes: 360, },
    { value: "Asia/Rangoon", label: "Asia - Rangoon (GMT+6:30)", offsetMinutes: 390, },
    { value: "Indian/Cocos", label: "Indian - Cocos (GMT+6:30)", offsetMinutes: 390, },
    { value: "Antarctica/Davis", label: "Antarctica - Davis (GMT+7)", offsetMinutes: 420, },
    { value: "Asia/Bangkok", label: "Asia - Bangkok (GMT+7)", offsetMinutes: 420, },
    { value: "Asia/Barnaul", label: "Asia - Barnaul (GMT+7)", offsetMinutes: 420, },
    { value: "Asia/Hovd", label: "Asia - Hovd (GMT+7)", offsetMinutes: 420, },
    { value: "Asia/Jakarta", label: "Asia - Jakarta (GMT+7)", offsetMinutes: 420, },
    { value: "Asia/Krasnoyarsk", label: "Asia - Krasnoyarsk (GMT+7)", offsetMinutes: 420, },
    { value: "Asia/Novokuznetsk", label: "Asia - Novokuznetsk (GMT+7)", offsetMinutes: 420, },
    { value: "Asia/Novosibirsk", label: "Asia - Novosibirsk (GMT+7)", offsetMinutes: 420, },
    { value: "Asia/Phnom_Penh", label: "Asia - Phnom Penh (GMT+7)", offsetMinutes: 420, },
    { value: "Asia/Pontianak", label: "Asia - Pontianak (GMT+7)", offsetMinutes: 420, },
    { value: "Asia/Saigon", label: "Asia - Saigon (GMT+7)", offsetMinutes: 420, },
    { value: "Asia/Tomsk", label: "Asia - Tomsk (GMT+7)", offsetMinutes: 420, },
    { value: "Asia/Vientiane", label: "Asia - Vientiane (GMT+7)", offsetMinutes: 420, },
    { value: "Indian/Christmas", label: "Indian - Christmas (GMT+7)", offsetMinutes: 420, },
    { value: "Antarctica/Casey", label: "Antarctica - Casey (GMT+8)", offsetMinutes: 480, },
    { value: "Asia/Brunei", label: "Asia - Brunei (GMT+8)", offsetMinutes: 480, },
    { value: "Asia/Hong_Kong", label: "Asia - Hong Kong (GMT+8)", offsetMinutes: 480, },
    { value: "Asia/Irkutsk", label: "Asia - Irkutsk (GMT+8)", offsetMinutes: 480, },
    { value: "Asia/Kuala_Lumpur", label: "Asia - Kuala Lumpur (GMT+8)", offsetMinutes: 480, },
    { value: "Asia/Kuching", label: "Asia - Kuching (GMT+8)", offsetMinutes: 480, },
    { value: "Asia/Macau", label: "Asia - Macau (GMT+8)", offsetMinutes: 480, },
    { value: "Asia/Makassar", label: "Asia - Makassar (GMT+8)", offsetMinutes: 480, },
    { value: "Asia/Manila", label: "Asia - Manila (GMT+8)", offsetMinutes: 480, },
    { value: "Asia/Shanghai", label: "Asia - Shanghai (GMT+8)", offsetMinutes: 480, },
    { value: "Asia/Singapore", label: "Asia - Singapore (GMT+8)", offsetMinutes: 480, },
    { value: "Asia/Taipei", label: "Asia - Taipei (GMT+8)", offsetMinutes: 480, },
    { value: "Asia/Ulaanbaatar", label: "Asia - Ulaanbaatar (GMT+8)", offsetMinutes: 480, },
    { value: "Australia/Perth", label: "Australia - Perth (GMT+8)", offsetMinutes: 480, },
    { value: "Australia/Eucla", label: "Australia - Eucla (GMT+8:45)", offsetMinutes: 525, },
    { value: "Asia/Chita", label: "Asia - Chita (GMT+9)", offsetMinutes: 540, },
    { value: "Asia/Dili", label: "Asia - Dili (GMT+9)", offsetMinutes: 540, },
    { value: "Asia/Jayapura", label: "Asia - Jayapura (GMT+9)", offsetMinutes: 540, },
    { value: "Asia/Khandyga", label: "Asia - Khandyga (GMT+9)", offsetMinutes: 540, },
    { value: "Asia/Pyongyang", label: "Asia - Pyongyang (GMT+9)", offsetMinutes: 540, },
    { value: "Asia/Seoul", label: "Asia - Seoul (GMT+9)", offsetMinutes: 540, },
    { value: "Asia/Tokyo", label: "Asia - Tokyo (GMT+9)", offsetMinutes: 540, },
    { value: "Asia/Yakutsk", label: "Asia - Yakutsk (GMT+9)", offsetMinutes: 540, },
    { value: "Pacific/Palau", label: "Pacific - Palau (GMT+9)", offsetMinutes: 540, },
    { value: "Australia/Darwin", label: "Australia - Darwin (GMT+9:30)", offsetMinutes: 570, },
    { value: "Antarctica/DumontDUrville", label: "Antarctica - DumontDUrville (GMT+10)", offsetMinutes: 600, },
    { value: "Asia/Ust-Nera", label: "Asia - Ust-Nera (GMT+10)", offsetMinutes: 600, },
    { value: "Asia/Vladivostok", label: "Asia - Vladivostok (GMT+10)", offsetMinutes: 600, },
    { value: "Australia/Brisbane", label: "Australia - Brisbane (GMT+10)", offsetMinutes: 600, },
    { value: "Australia/Lindeman", label: "Australia - Lindeman (GMT+10)", offsetMinutes: 600, },
    { value: "Pacific/Guam", label: "Pacific - Guam (GMT+10)", offsetMinutes: 600, },
    { value: "Pacific/Port_Moresby", label: "Pacific - Port Moresby (GMT+10)", offsetMinutes: 600, },
    { value: "Pacific/Saipan", label: "Pacific - Saipan (GMT+10)", offsetMinutes: 600, },
    { value: "Pacific/Truk", label: "Pacific - Truk (GMT+10)", offsetMinutes: 600, },
    { value: "Australia/Adelaide", label: "Australia - Adelaide (GMT+10:30)", offsetMinutes: 630, },
    { value: "Australia/Broken_Hill", label: "Australia - Broken Hill (GMT+10:30)", offsetMinutes: 630, },
    { value: "Antarctica/Macquarie", label: "Antarctica - Macquarie (GMT+11)", offsetMinutes: 660, },
    { value: "Asia/Magadan", label: "Asia - Magadan (GMT+11)", offsetMinutes: 660, },
    { value: "Asia/Sakhalin", label: "Asia - Sakhalin (GMT+11)", offsetMinutes: 660, },
    { value: "Asia/Srednekolymsk", label: "Asia - Srednekolymsk (GMT+11)", offsetMinutes: 660, },
    { value: "Australia/Hobart", label: "Australia - Hobart (GMT+11)", offsetMinutes: 660, },
    { value: "Australia/Lord_Howe", label: "Australia - Lord Howe (GMT+11)", offsetMinutes: 660, },
    { value: "Australia/Melbourne", label: "Australia - Melbourne (GMT+11)", offsetMinutes: 660, },
    { value: "Australia/Sydney", label: "Australia - Sydney (GMT+11)", offsetMinutes: 660, },
    { value: "Pacific/Bougainville", label: "Pacific - Bougainville (GMT+11)", offsetMinutes: 660, },
    { value: "Pacific/Efate", label: "Pacific - Efate (GMT+11)", offsetMinutes: 660, },
    { value: "Pacific/Guadalcanal", label: "Pacific - Guadalcanal (GMT+11)", offsetMinutes: 660, },
    { value: "Pacific/Kosrae", label: "Pacific - Kosrae (GMT+11)", offsetMinutes: 660, },
    { value: "Pacific/Noumea", label: "Pacific - Noumea (GMT+11)", offsetMinutes: 660, },
    { value: "Pacific/Ponape", label: "Pacific - Ponape (GMT+11)", offsetMinutes: 660, },
    { value: "Asia/Anadyr", label: "Asia - Anadyr (GMT+12)", offsetMinutes: 720, },
    { value: "Asia/Kamchatka", label: "Asia - Kamchatka (GMT+12)", offsetMinutes: 720, },
    { value: "Pacific/Fiji", label: "Pacific - Fiji (GMT+12)", offsetMinutes: 720, },
    { value: "Pacific/Funafuti", label: "Pacific - Funafuti (GMT+12)", offsetMinutes: 720, },
    { value: "Pacific/Kwajalein", label: "Pacific - Kwajalein (GMT+12)", offsetMinutes: 720, },
    { value: "Pacific/Majuro", label: "Pacific - Majuro (GMT+12)", offsetMinutes: 720, },
    { value: "Pacific/Nauru", label: "Pacific - Nauru (GMT+12)", offsetMinutes: 720, },
    { value: "Pacific/Norfolk", label: "Pacific - Norfolk (GMT+12)", offsetMinutes: 720, },
    { value: "Pacific/Tarawa", label: "Pacific - Tarawa (GMT+12)", offsetMinutes: 720, },
    { value: "Pacific/Wake", label: "Pacific - Wake (GMT+12)", offsetMinutes: 720, },
    { value: "Pacific/Wallis", label: "Pacific - Wallis (GMT+12)", offsetMinutes: 720, },
    { value: "Antarctica/McMurdo", label: "Antarctica - McMurdo (GMT+13)", offsetMinutes: 780, },
    { value: "Pacific/Apia", label: "Pacific - Apia (GMT+13)", offsetMinutes: 780, },
    { value: "Pacific/Auckland", label: "Pacific - Auckland (GMT+13)", offsetMinutes: 780, },
    { value: "Pacific/Enderbury", label: "Pacific - Enderbury (GMT+13)", offsetMinutes: 780, },
    { value: "Pacific/Fakaofo", label: "Pacific - Fakaofo (GMT+13)", offsetMinutes: 780, },
    { value: "Pacific/Tongatapu", label: "Pacific - Tongatapu (GMT+13)", offsetMinutes: 780, },
    { value: "Pacific/Chatham", label: "Pacific - Chatham (GMT+13:45)", offsetMinutes: 825, },
    { value: "Pacific/Kiritimati", label: "Pacific - Kiritimati (GMT+14)", offsetMinutes: 840, },
];

/** True when `value` is a known IANA time-zone id in TIMEZONES. */
export function isKnownTimeZone(value: string,): boolean {
    return TIMEZONES.some((t,) => t.value === value,);
}
