-- @feature mailing_lists
--
-- Extra `{{ }}` variables for one send job.
--
-- The worker resolves a job's rendered HTML per recipient against a context
-- built from the SUBSCRIBER (name, email, list, unsubscribe URL). That is all a
-- hand-composed campaign needs, because a human already typed the content.
--
-- A send generated by a FEATURE also has data of its own: the new-merchandise
-- announcement carries the products it is announcing, so an operator-authored
-- template can write `{{ for products as p }}`. Those values are identical for
-- every recipient, but they have to survive the process boundary — the job may
-- be resumed by a different process hours later, so they cannot live in memory.
--
-- Nullable: every existing job, and every hand-composed send, has none.
ALTER TABLE mail_send_jobs
    ADD COLUMN IF NOT EXISTS context JSONB;
